// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Item struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type PasswordResetToken struct {
	Email     string       `json:"email"`
	Token     string       `json:"token"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Session struct {
	ID           string         `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Payload      string         `json:"payload"`
	LastActivity int32          `json:"last_activity"`
}

type User struct {
	ID                int32          `json:"id"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	Email             string         `json:"email"`
	EmailVerifiedAt   sql.NullTime   `json:"email_verified_at"`
	RoleID            int32          `json:"role_id"`
	RememberTokenUuid sql.NullString `json:"remember_token_uuid"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}
